# cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  # This step uses the Docker builder to build your image.
  # It tags the image with the Artifact Registry path and the commit SHA.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--tag'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY_NAME}/${_IMAGE_NAME}:latest' # Optional: also tag as latest

      # Pass build-time arguments defined in your Dockerfile
      # IMPORTANT: Replace these with your actual values!
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://user-server-bh-168223699989.us-central1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_Y2xlYXItZm93bC0wLmNsZXJrLmFjY291bnRzLmRldiQ'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/'
      - '.' # Docker build context (current directory)
    id: 'Build Docker Image'
    timeout: '1200s' # Optional: Increase timeout if build takes longer

  # Step 2: Push the Docker image to Artifact Registry
  # This step pushes the tagged image to your Artifact Registry repository.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
    id: 'Push Image to Artifact Registry (commit sha)'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY_NAME}/${_IMAGE_NAME}:latest' # Optional: push latest tag
    id: 'Push Image to Artifact Registry (latest)'

# Specify the images to be built and pushed.
# This is important for Cloud Build to know what artifacts were produced.
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY_NAME}/${_IMAGE_NAME}:latest' # Optional: if you pushed latest

# Substitutions: These are variables you can override at build time or set as defaults.
substitutions:
  _REGION: 'us-central1'                 # Replace with your Artifact Registry region
  _AR_REPOSITORY_NAME: 'my-nextjs-apps'  # Replace with your Artifact Registry repository name
  _IMAGE_NAME: 'bh-admin-panel'          # Replace with your desired image name

# Options for the build
options:
  logging: CLOUD_LOGGING_ONLY # Store logs in Cloud Logging
  # machineType: 'E2_HIGHCPU_8' # Optional: Specify a more powerful machine type if needed